server.port: 8080

# Dubbo 配置
spring.dubbo:
  application.name: crm-order
  server: true
  protocol:
    host: 192.168.37.1
    name: dubbo
    port: 20880
  registry.address: zookeeper://127.0.0.1:2181