server.port: 8081

# Dubbo 配置
spring.dubbo:
  application.name: crm-upc
  server: true
  protocol:
    host: 192.168.37.1
    name: dubbo
    port: 20881
  registry.address: zookeeper://127.0.0.1:2181